In [30]:
## Crear entorno virtual
## python3 -m venv venv
## Activar entorno virtual
## source venv/bin/activate

In [109]:
!pip install pandas scikit-learn fastapi

Requirement already satisfied: pandas in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (2.0.3)
Requirement already satisfied: scikit-learn in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (1.3.2)
Collecting fastapi
  Downloading fastapi-0.109.1-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from pandas) (2023.4)
Requirement already satisfied: numpy>=1.20.3 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from pandas) (1.24.4)
Requirement already satisfied: scipy>=1.5.0 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from scikit-learn) (3.2.0)
Collecting pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 (from fastapi)
  Downloading pydantic-2.6.0-py3-none-any.whl.metadata (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 2.5 MB/s eta 0:00:00
Collecting starlette<0.36.0,>=0.35.0 (from fastapi)
  Downloading starlette-0.35.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from fastapi) (4.9.0)
Collecting annotated-types>=0.4.0 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi)
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.16.1 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi)
  Downloading pydantic_core-2.16.1-cp38-cp38-macosx_10_12_x86_64.whl.metadata (6.5 kB)
Requirement already satisfied: six>=1.5 in /Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting anyio<5,>=3.4.0 (from starlette<0.36.0,>=0.35.0->fastapi)
  Downloading anyio-4.2.0-py3-none-any.whl.metadata (4.6 kB)
Collecting idna>=2.8 (from anyio<5,>=3.4.0->starlette<0.36.0,>=0.35.0->fastapi)
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting sniffio>=1.1 (from anyio<5,>=3.4.0->starlette<0.36.0,>=0.35.0->fastapi)
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting exceptiongroup>=1.0.2 (from anyio<5,>=3.4.0->starlette<0.36.0,>=0.35.0->fastapi)
  Downloading exceptiongroup-1.2.0-py3-none-any.whl.metadata (6.6 kB)
Downloading fastapi-0.109.1-py3-none-any.whl (92 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 kB 3.2 MB/s eta 0:00:00
Downloading pydantic-2.6.0-py3-none-any.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.2/394.2 kB 9.9 MB/s eta 0:00:00:00:01
Downloading pydantic_core-2.16.1-cp38-cp38-macosx_10_12_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 35.9 MB/s eta 0:00:00:00:01
Downloading starlette-0.35.1-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.1/71.1 kB 2.3 MB/s eta 0:00:00
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading anyio-4.2.0-py3-none-any.whl (85 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 kB 2.9 MB/s eta 0:00:00
Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 2.1 MB/s eta 0:00:00
Installing collected packages: sniffio, pydantic-core, idna, exceptiongroup, annotated-types, pydantic, anyio, starlette, fastapi
Successfully installed annotated-types-0.6.0 anyio-4.2.0 exceptiongroup-1.2.0 fastapi-0.109.1 idna-3.6 pydantic-2.6.0 pydantic-core-2.16.1 sniffio-1.3.0 starlette-0.35.1

In [32]:
import pandas as pd

In [206]:
## Cargar datos
data = pd.read_csv('data/penguins_lter.csv')
data = data.rename(columns={"Flipper Length (mm)": "FlipperLength_mm",
                     "Body Mass (g)":"BodyMass_g",
                     "Culmen Length (mm)":"CulmenLength_mm",
                     "Culmen Depth (mm)":"CulmenDepth_mm",
                     "Date Egg":"DateEgg"})

features = ["FlipperLength_mm",  "BodyMass_g",
            "CulmenLength_mm", "CulmenDepth_mm", 
            "Island", "DateEgg","Species"]

data = data[features].dropna()
data['DateEgg'] = data['DateEgg'].apply(lambda x: x.split('/')[0]).astype(int)

data

,FlipperLength_mm,BodyMass_g,CulmenLength_mm,CulmenDepth_mm,Island,DateEgg,Species
0,181.0,3750.0,39.1,18.7,Torgersen,11,Adelie Penguin (Pygoscelis adeliae)
1,186.0,3800.0,39.5,17.4,Torgersen,11,Adelie Penguin (Pygoscelis adeliae)
2,195.0,3250.0,40.3,18.0,Torgersen,11,Adelie Penguin (Pygoscelis adeliae)
4,193.0,3450.0,36.7,19.3,Torgersen,11,Adelie Penguin (Pygoscelis adeliae)
5,190.0,3650.0,39.3,20.6,Torgersen,11,Adelie Penguin (Pygoscelis adeliae)
...,...,...,...,...,...,...,...
338,214.0,4925.0,47.2,13.7,Biscoe,12,Gentoo penguin (Pygoscelis papua)
340,215.0,4850.0,46.8,14.3,Biscoe,11,Gentoo penguin (Pygoscelis papua)
341,222.0,5750.0,50.4,15.7,Biscoe,11,Gentoo penguin (Pygoscelis papua)
342,212.0,5200.0,45.2,14.8,Biscoe,11,Gentoo penguin (Pygoscelis papua)
343,213.0,5400.0,49.9,16.1,Biscoe,11,Gentoo penguin (Pygoscelis papua)

In [207]:
from sklearn.preprocessing import LabelEncoder
from joblib import dump
label_encoder = LabelEncoder() 

for i in data.columns:
    if data[i].dtype == "object":
        label_encoder.fit_transform(list(data[i].values))
        data[i] = label_encoder.transform(data[i].values)
        if i=='Island':
            dump(label_encoder,'Island_Encoder.joblib')
data

,FlipperLength_mm,BodyMass_g,CulmenLength_mm,CulmenDepth_mm,Island,DateEgg,Species
0,181.0,3750.0,39.1,18.7,2,11,0
1,186.0,3800.0,39.5,17.4,2,11,0
2,195.0,3250.0,40.3,18.0,2,11,0
4,193.0,3450.0,36.7,19.3,2,11,0
5,190.0,3650.0,39.3,20.6,2,11,0
...,...,...,...,...,...,...,...
338,214.0,4925.0,47.2,13.7,0,12,2
340,215.0,4850.0,46.8,14.3,0,11,2
341,222.0,5750.0,50.4,15.7,0,11,2
342,212.0,5200.0,45.2,14.8,0,11,2
343,213.0,5400.0,49.9,16.1,0,11,2

In [208]:
x = data.drop(columns=['Species'])
y = data['Species']

In [218]:
x

,FlipperLength_mm,BodyMass_g,CulmenLength_mm,CulmenDepth_mm,Island,DateEgg
0,181.0,3750.0,39.1,18.7,2,11
1,186.0,3800.0,39.5,17.4,2,11
2,195.0,3250.0,40.3,18.0,2,11
4,193.0,3450.0,36.7,19.3,2,11
5,190.0,3650.0,39.3,20.6,2,11
...,...,...,...,...,...,...
338,214.0,4925.0,47.2,13.7,0,12
340,215.0,4850.0,46.8,14.3,0,11
341,222.0,5750.0,50.4,15.7,0,11
342,212.0,5200.0,45.2,14.8,0,11
343,213.0,5400.0,49.9,16.1,0,11

In [209]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y, random_state=42, 
    test_size=.2, stratify=y
)

In [210]:
from sklearn import svm


clf = svm.SVC()
clf.fit(x, y)
dump(clf, 'penguin_model.joblib')

['penguin_model.joblib']

In [224]:
print(clf.predict([X_test.iloc[0]]))
print(y_test.iloc[0])

[0]
0

/Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [212]:
from fastapi import FastAPI, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel
from joblib import load

In [213]:
class Penguin(BaseModel):
    studyName: str = "PAL0708"
    SampleNumber: int = 1
    Region: str = "Anvers"
    Island: str = "Torgersen"
    Stage: str = "Adult, 1 Egg Stage"
    IndividualID: str = "N1A1"
    ClutchCompletion: str = "Yes"
    DateEgg: str = "11/11/07"
    CulmenLength_mm: float = 39.1
    CulmenDepth_mm: float = 18.7
    FlipperLength_mm: float = 181.0
    BodyMass_g: float = 3750.0
    Sex: str = "MALE"
    Delta_15_N: str = "NaN"
    Delta_13_C: str = "NaN"
    Comments: str = "Not enough blood for isotopes."

In [214]:
from os.path import exists
def loadLabelEncoder(file_name: str = 'Island_Encoder.joblib')->LabelEncoder():
    """
    Load label encoder
    input:
        file_name: Name of file encoded as joblib 
    output:
        loaded LabelEncoder Object
    """
    assert exists(file_name)
    assert file_name.endswith('.joblib')
    return load(file_name)
def loadSVCModel(file_name: str ='penguin_model.joblib') -> svm.SVC():
    """
    Load SVC model
    input:
        file_name: Name of file encoded as joblib 
    output:
        loaded svm.SVC Object
    """
    assert exists(file_name)
    assert file_name.endswith('.joblib')
    return load(file_name)

Island_Encoder = loadLabelEncoder()
model_loaded = loadSVCModel()

In [227]:

from typing import List
def process_penguin(penguin: Penguin) -> List:
    """
    From Pydantic Model process data to use SVC model, required as list
    input:
        penguin: Pydantic Model 
    output:
        list of fields required to do inference
    """
    penguin_dict = penguin.model_dump(include=["FlipperLength_mm",  "BodyMass_g",
                                               "CulmenLength_mm", "CulmenDepth_mm",
                                               "Island", "DateEgg"])
    penguin_df = pd.DataFrame([penguin_dict])
    penguin_df['DateEgg'] = penguin_df['DateEgg'].apply(lambda x: x.split('/')[0]).astype(int)
    penguin_df['Island'] = Island_Encoder.transform(penguin_df['Island'])
    return [penguin_df.iloc[0]]

def inference_penguin(model: svm.SVC(), penguin: List):
    """
    do inference of saved model
    input:
        penguin: list of fields required to do inference 
    output:
        number of class predicted
    """
    return model.predict(penguin)[0]

In [228]:
penguin = Penguin()
penguin_list = process_penguin(penguin)
penguin_list#.rename_axis
inference_penguin(model_loaded, penguin_list)

/Users/cristiandiazalvarez/Documents/JAVERIANA/CLASES/MAESTRIA/MLOPS/MLOPS_PUJ_V1/.venv/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

0